spring:
  application:
    name: "hive-service"
  datasource:
    url: jdbc:h2:mem:hive-db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
